name: PlantsPlacementPlugin
version: '1.0.3'
main: com.illia.plantsPlacementPlugin.Main
api-version: '1.21'
authors: [ Illia ]
description: Paper plugin to place various plants on any blocks
commands:
  plantsplacement:
